# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'par-ou-impar' do

use_frameworks!

pod 'Alamofire', '~> 1.2'
pod 'AlamofireObjectMapper', '~> 0.2'
pod 'Parse'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'

end

target 'par-ou-imparTests' do

end

